// Generated by gencpp from file vr_teleoperation_msg/IKPose.msg
// DO NOT EDIT!


#ifndef VR_TELEOPERATION_MSG_MESSAGE_IKPOSE_H
#define VR_TELEOPERATION_MSG_MESSAGE_IKPOSE_H

#include <ros/service_traits.h>


#include <vr_teleoperation_msg/IKPoseRequest.h>
#include <vr_teleoperation_msg/IKPoseResponse.h>


namespace vr_teleoperation_msg
{

struct IKPose
{

typedef IKPoseRequest Request;
typedef IKPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IKPose
} // namespace vr_teleoperation_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vr_teleoperation_msg::IKPose > {
  static const char* value()
  {
    return "87c66b5bf696f783971b87b3f0518ef4";
  }

  static const char* value(const ::vr_teleoperation_msg::IKPose&) { return value(); }
};

template<>
struct DataType< ::vr_teleoperation_msg::IKPose > {
  static const char* value()
  {
    return "vr_teleoperation_msg/IKPose";
  }

  static const char* value(const ::vr_teleoperation_msg::IKPose&) { return value(); }
};


// service_traits::MD5Sum< ::vr_teleoperation_msg::IKPoseRequest> should match
// service_traits::MD5Sum< ::vr_teleoperation_msg::IKPose >
template<>
struct MD5Sum< ::vr_teleoperation_msg::IKPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vr_teleoperation_msg::IKPose >::value();
  }
  static const char* value(const ::vr_teleoperation_msg::IKPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vr_teleoperation_msg::IKPoseRequest> should match
// service_traits::DataType< ::vr_teleoperation_msg::IKPose >
template<>
struct DataType< ::vr_teleoperation_msg::IKPoseRequest>
{
  static const char* value()
  {
    return DataType< ::vr_teleoperation_msg::IKPose >::value();
  }
  static const char* value(const ::vr_teleoperation_msg::IKPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vr_teleoperation_msg::IKPoseResponse> should match
// service_traits::MD5Sum< ::vr_teleoperation_msg::IKPose >
template<>
struct MD5Sum< ::vr_teleoperation_msg::IKPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vr_teleoperation_msg::IKPose >::value();
  }
  static const char* value(const ::vr_teleoperation_msg::IKPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vr_teleoperation_msg::IKPoseResponse> should match
// service_traits::DataType< ::vr_teleoperation_msg::IKPose >
template<>
struct DataType< ::vr_teleoperation_msg::IKPoseResponse>
{
  static const char* value()
  {
    return DataType< ::vr_teleoperation_msg::IKPose >::value();
  }
  static const char* value(const ::vr_teleoperation_msg::IKPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VR_TELEOPERATION_MSG_MESSAGE_IKPOSE_H
